### ISSUE TITLE
FYI - 2022 edition

### ISSUE THREAD

**Issue by louispotok** [datasets/harmonized-system#1]
First -- this is incredible, thanks so much for putting it together! Second, just letting you know that there is a new edition for 2022. Looks like it is already on the WCO site but not yet on Comtrade. Do you have some easy way to create the dataset from the WCO PDFs, or another data source? If not, is there any way I can help?

**Comment by sabas** [comment]
Hi, my first attempt was to convert the WCO pdfs but it came to be mostly a manual work so I didn't complete that, I found the excel from Comtrade and converted it...
So, either we wait for that release or we apply the amendments from WCO pdf
http://www.wcoomd.org/en/topics/nomenclature/instrument-and-tools/hs-nomenclature-2022-edition/amendments-effective-from-1-january-2022.aspx

But I wonder if it is worth the effort...

**Comment by louispotok** [comment]
Waiting for the Comtrade release seems very sensible.

**Comment by mikerockett** [comment]
@sabas I'm also waiting patiently for a new dataset to be released by Comtrade – surprised they haven't done so yet. Also wish they had JSON correlation tables so that existing 2017 datasets could be upgraded easily. 😔

**Comment by sabas** [comment]
@mikerockett @louispotok fixed by ̀#2

**Comment by abid-omar** [comment]
Thank you so much for keeping this updated.
